### ISSUE TITLE
printStr does nothing

### ISSUE THREAD

**Issue by FranzPichardoR** [moezbaccouche/react-native-pax-library#6]
I am trying to print on a Pax A920Pro with Android 7.1. I am using react-native ~0.63.4, react-native-pax-library ^1.0.2, and my targetSdkVersion is 30 (don't know if that helps). Like i said, i am trying to print but it doesn't work. 
Its throwing me this error:
**`PrintManager: NO PERMISSION:0x60000202`**
Can someone help me with this?

**Comment by moezbaccouche** [comment]
Hi @FranzPichardoR , I think A920Pro devices need a specific permission in order to use the printer. Please try to add this line inside `AndroidManifest.xml`
```xml
<uses-permission android:name="com.pax.permission.PRINTER" />
```

**Comment by FranzPichardoR** [comment]
Thank you so much @moezbaccouche ! That was exactly it. Also thank you for the fast reply. Have a great day.
